const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
class Element{constructor(){this.handlers={};this.style={};this.dataset={};this.open=false;this.classList={contains:()=>false};}addEventListener(k,f){(this.handlers[k]??=[]).push(f)}fire(k,e={}){for(const f of this.handlers[k]||[])f({preventDefault(){},target:{closest:()=>null},button:0,...e})}setAttribute(){}setPointerCapture(){}getBoundingClientRect(){return{left:0,top:0,width:58,height:58}}showModal(){this.open=true}close(){this.open=false;this.fire('close')}focus(){}}
const elements={};const el=id=>elements[id]??=new Element();const buttons=['left','up','down','right'].map(d=>{const e=new Element();e.dataset.aim=d;return e});const modes=['joystick','buttons','keyboard'].map(d=>{const e=new Element();e.dataset.controlMode=d;return e});
let callback,now=0,saved;const w=new Element(),doc=new Element();doc.getElementById=el;doc.querySelectorAll=s=>s==='[data-aim]'?buttons:modes;doc.hidden=false;
const c=vm.createContext({document:doc,window:w,localStorage:{getItem:()=>null,setItem:(k,v)=>saved=JSON.parse(v)},performance:{now:()=>now},requestAnimationFrame:f=>{callback=f;return 1},cancelAnimationFrame:()=>{callback=null},BOT_LEVELS:{easy:{},expert:{}},fieldOrientation:'vertical',botDifficulty:'expert',aimAngle:0,aimPower:.5,gameMode:'local',onlineRoomCode:'',humanTurn:()=>c.turn,turn:true,setupOverlay:new Element(),modal:new Element(),fieldVerticalBtn:new Element(),fieldHorizontalBtn:new Element(),aiEasyBtn:new Element(),aiMediumBtn:new Element(),aiHardBtn:new Element(),aiExpertBtn:new Element()});
c.updateUI=()=>vm.runInContext('renderAimControls()',c);vm.runInContext(fs.readFileSync(require('path').join(__dirname,'settings.js'),'utf8'),c);
const frame=()=>{now+=16;callback?.(now)};const tick=()=>{for(let i=0;i<20;i++)frame()};const run=s=>vm.runInContext(s,c);
modes[1].fire('click');buttons[3].fire('click',{detail:0});assert.equal(c.aimAngle,1);
buttons[1].fire('pointerdown',{pointerId:1});tick();assert(c.aimPower>.55);buttons[1].fire('pointerup',{pointerId:1});frame();const stopped=c.aimPower;tick();assert.equal(c.aimPower,stopped);
modes[2].fire('click');w.fire('keydown',{code:'KeyD'});tick();assert(c.aimAngle>1);w.fire('blur');const angle=c.aimAngle;tick();assert.equal(c.aimAngle,angle);
w.fire('keydown',{code:'KeyA',target:{closest:()=>({})}});tick();assert.equal(c.aimAngle,angle);
w.fire('keydown',{code:'ArrowLeft'});tick();assert(c.aimAngle<angle);el('settingsBtn').fire('click');const paused=c.aimAngle;tick();assert.equal(c.aimAngle,paused);assert(el('settingsDialog').open);el('settingsDialog').close();
modes[0].fire('click');el('joystickControl').fire('pointerdown',{pointerId:4,clientX:53,clientY:5});tick();assert(c.aimAngle>paused);el('joystickControl').fire('pointercancel',{pointerId:4});const after=c.aimAngle;tick();assert.equal(c.aimAngle,after);
c.turn=false;el('joystickControl').fire('pointerdown',{pointerId:5,clientX:53,clientY:5});tick();assert.equal(c.aimAngle,after);
c.turn=true;c.aimAngle=58;c.aimPower=1;modes[1].fire('click');buttons[3].fire('click',{detail:0});buttons[1].fire('click',{detail:0});assert.equal(c.aimAngle,58);assert.equal(c.aimPower,1);assert.equal(saved.controlMode,'buttons');
c.gameMode='online';c.onlineRoomCode='ABCDE';el('settingsBtn').fire('click');assert(c.fieldVerticalBtn.disabled);assert(c.fieldHorizontalBtn.disabled);
console.log('PASS: buttons, hold/release, WASD, arrows, blur, text-input exclusion, modal blocking, joystick, cancel, turn lock, limits, persistence, online orientation lock');
